name: Android TV Card
description: 📺 Android TV Remote Card
version: 1.3.0
type: lovelace
keywords:
  - androidtv
  - android
  - googletv
  - google
  - tvcard
  - remote
  - tv
  - television
author:
  name: Nerwyn
license: Apache License, Version 2.0
files:
  - android-tv-card.js
  - android-tv-card-editor.js
