name: Android TV Card
description: 📺 Android TV Remote Card
version: 1.3.3
type: lovelace
keywords:
  - androidtv
  - android
  - googletv
  - google
  - tvcard
  - remote
  - tv
  - television
author:
  name: Nerwyn
license: Apache License, Version 2.0
files:
  - android-tv-card.js
  - android-tv-card-editor.js
bugs:
  url: https://github.com/Nerwyn/android-tv-card/issues
homepage: https://github.com/Nerwyn/android-tv-card#readme
repository:
  type: git
  url: git+https://github.com/Nerwyn/android-tv-card.git
